name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Remove this step if you don't need Docker Buildx
      #- name: Set up Docker Buildx
       # uses: docker/setup-buildx-action@v1

#      - name: Log in to Docker Hub
 #       run: |
  #        echo "DOCKER_ID: ${DOCKER_ID}"
   #       echo "DOCKER_PASSWORD: ${DOCKER_PASSWORD}"
    #      echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_ID}" --password-stdin

   #   - name: Build and push Docker image
  #      run: |
 #         docker-compose build
#          docker-compose push

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform plan


      - name: Terraform Apply
        run: terraform apply -auto-approve

    #  - name: Sleep for 2 minutes
     #   run: sleep 2m

    #  - name: Docker Compose Down
    #    run: docker-compose down

      #- name: Stop EC2 Instances
       # run: |
        #  aws ec2 stop-instances --instance-ids i-0ae886df663d67fe0 --region us-east-1
